### ISSUE TITLE
Plugin does not work since v3.9.1

### ISSUE THREAD

**Issue by nenadfilipovic** [testing-library/eslint-plugin-jest-dom#196] opened 2021-09-12 12:35 UTC
- `eslint-plugin-jest-dom` version:3.9.2
- `node` version:14.17.5
- `npm` version: 6.14.14

Something changed from 3.9.0 (which works fine) to 3.9.1 and 3.9.2 that kills my eslint.
Here is config:

```
 "extends": [
    ...
    "plugin:jest-dom/recommended",
    ...
  ],
```

```
[Error - 12:29:17 PM] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Failed to load plugin 'jest-dom' declared in '.eslintrc.json': Cannot find module '/workspace/node_modules/eslint-plugin-jest-dom/dist/index.js'. Please verify that the package.json has a valid "main" entry
Require stack:
- /workspace/__placeholder__.js
Referenced from: /workspace/.eslintrc.json
  Code: -32603 
(node:1310) UnhandledPromiseRejectionWarning: Error: Failed to load plugin 'jest-dom' declared in '.eslintrc.json': Cannot find module '/workspace/node_modules/eslint-plugin-jest-dom/dist/index.js'. Please verify that the package.json has a valid "main" entry
Require stack:
- /workspace/__placeholder__.js
Referenced from: /workspace/.eslintrc.json
    at tryPackage (internal/modules/cjs/loader.js:303:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:516:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.resolve (/workspace/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadPlugin (/workspace/node_modules/@eslint/eslintrc/lib/config-array-factory.js:1017:39)
    at ConfigArrayFactory._loadExtendedPluginConfig (/workspace/node_modules/@eslint/eslintrc/lib/config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (/workspace/node_modules/@eslint/eslintrc/lib/config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/workspace/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/workspace/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/workspace/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/workspace/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/workspace/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/workspace/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/workspace/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/workspace/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:300:18)
    at CLIEngine.getConfigForFile (/workspace/node_modules/eslint/lib/cli-engine/cli-engine.js:953:14)
    at _e.calculateConfigForFile (/home/node/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.25/server/out/eslintServer.js:1:177670)
    at /home/node/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.25/server/out/eslintServer.js:1:166999
    at Re (/home/node/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.25/server/out/eslintServer.js:1:177178)
    at f.then.s.validate (/home/node/.vscode-server/extensions/dbaeumer.vscode-eslint-2.1.25/server/out/eslintServer.js:1:166978)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:1310) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 14)
```

**Comment by MichaelDeBoey** [comment] 2021-09-12 13:24
Duplicate of #194

**Closed by MichaelDeBoey** 2021-09-12 13:24 UTC
